"""Added rooms column

Revision ID: a53220af0a53
Revises: e5e9db8e81d9
Create Date: 2026-03-09 12:40:54.798491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53220af0a53'
down_revision = 'e5e9db8e81d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms', sa.Integer(), nullable=True))
        batch_op.drop_column('bedrooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('rooms')

    # ### end Alembic commands ###
